### ISSUE TITLE
有没有指定网卡的办法

### ISSUE THREAD

**Issue by anglabace** [xuchao1213/AliyunDdnsCSharp#14]
有没有指定网卡的办法

**Comment by xuchao1213** [comment]
> 有没有指定网卡的办法

你想指定网卡类型还是指定到具体的网卡

**Comment by anglabace** [comment]
@xuchao1213 具体的网卡。
还有个建议就是 ipv6 ddns的域名是否能数组形式 毕竟会遇到一个问题一个可能会存在多个不同运营商的ipv6地址。如果存在多个ipv6地址且只有一个域名那就默认为多个ip地址取第一条这种方式如果配置了两个域名那就按顺序第二个ip配置到第二个域名上。

**Comment by xuchao1213** [comment]
> @xuchao1213 具体的网卡。
> 还有个建议就是 ipv6 ddns的域名是否能数组形式 毕竟会遇到一个问题一个可能会存在多个不同运营商的ipv6地址。如果存在多个ipv6地址且只有一个域名那就默认为多个ip地址取第一条这种方式如果配置了两个域名那就按顺序第二个ip配置到第二个域名上。

多个不同运营商的Ipv6地址？你有多条不同运营商宽带么？还是你说的是很多个临时Ipv6地址？

**Comment by anglabace** [comment]
@xuchao1213 多条运营商宽带 我 电信移动联通 都有

**Comment by xuchao1213** [comment]
> @xuchao1213 多条运营商宽带 我 电信移动联通 都有

那我明白了，你电脑有多张网卡，每张网卡接不同的运营商，你想每张网卡都可以通过DDNS解析到不同的域名上去？

**Comment by anglabace** [comment]
@xuchao1213 
嗯你说的是其中一种情况。这种情况指定网卡就能解决。

还有一种情况 OPENWRT系统同时接两条宽带会导致一个网卡也会得到两个运营商的IPV6。就需要在绑定域名策略上花点心思吧

**Comment by seszu** [comment]
给赞！
