### ISSUE TITLE
为什么过一天，网站就打不开了

### ISSUE THREAD

**Issue by wahaobi** [xuchao1213/AliyunDdnsCSharp#16]

**Comment by xuchao1213** [comment]
> _No description provided._
什么意思

**Comment by wahaobi** [comment]
就是运行一天，浏览就上不了网了

**Comment by wahaobi** [comment]
我调的1分钟检测，是不是把DNS缓存搞乱了，就上不上了。

**Comment by xuchao1213** [comment]
> 我调的1分钟检测，是不是把DNS缓存搞乱了，就上不上了。

1分钟太短了，另外获取外网IP的url你配置的什么

**Comment by xuchao1213** [comment]
> > 我调的1分钟检测，是不是把DNS缓存搞乱了，就上不上了。
> 
> 1分钟太短了，另外获取外网IP的url你配置的什么

我程序里有逻辑的，如果已有的解析条目IP和当前一样是不进行更新的，有可能是程序没有获取到正确的IP地址

**Comment by wahaobi** [comment]
![image](https://user-images.githubusercontent.com/40647643/82136969-022f2c00-9846-11ea-9d3f-faacaed9b72a.png)

**Comment by wahaobi** [comment]
![image](https://user-images.githubusercontent.com/40647643/82136977-1d01a080-9846-11ea-91c2-8229dda1a40e.png)

**Comment by xuchao1213** [comment]
看配置没问题
