### ISSUE TITLE
请问可以支持开机自启动吗

### ISSUE THREAD

**Issue by idchangyifan** [xuchao1213/AliyunDdnsCSharp#17]
如题

**Comment by xuchao1213** [comment]
支持的，README的使用说明中有的
https://github.com/xuchao1213/AliyunDdnsCSharp#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
![image](https://user-images.githubusercontent.com/16534956/83701354-fc09bf80-a63b-11ea-9766-32228138a214.png)

安装后即为开机自启的服务
