### ISSUE TITLE
请问支持ipv4从ipconfig获取地址吗，因为有做内网ddns的需求

### ISSUE THREAD

**Issue by izyq** [xuchao1213/AliyunDdnsCSharp#19]

**Comment by xuchao1213** [comment]
> _No description provided.
现在不支持，可以增加支持

**Comment by izyq** [comment]
> 
> 
> > _No description provided.
> > 现在不支持，可以增加支持

好的 期待你的下一个版本哦

**Comment by ccfish86** [comment]
建议支持内网(CIDR)，或指定网卡，比如可以指定为 192.168.12 可获取 192.168.12.1-192.168.12.255间的IP

**Comment by xuchao1213** [comment]
> 建议支持内网(CIDR)，或指定网卡，比如可以指定为 192.168.12 可获取 192.168.12.1-192.168.12.255间的IP

OK,我最近抽时间支持下

**Comment by xuchao1213** [comment]
> 建议支持内网(CIDR)，或指定网卡，比如可以指定为 192.168.12 可获取 192.168.12.1-192.168.12.255间的IP

OK,我最近抽时间支持下
