### ISSUE TITLE
获取公网的IP的地址使用http://www.ip138.com无效

### ISSUE THREAD

**Issue by seszu** [xuchao1213/AliyunDdnsCSharp#2]
"GetIpUrls"选项下只有使用http://ip.hiyun.me才能获取到公网IP信息，在日志里可以看到http://www.ip138.com和https://ip.cn均无法得到公网IP信息，是输入的网址不对吗。

**Comment by xuchao1213** [comment]
> "GetIpUrls"选项下只有使用[http://ip.hiyun.me才能获取到公网IP信息，在日志里可以看到http://www.ip138.com和https://ip.cn均无法得到公网IP信息，是输入的网址不对吗。](http://ip.hiyun.me%E6%89%8D%E8%83%BD%E8%8E%B7%E5%8F%96%E5%88%B0%E5%85%AC%E7%BD%91IP%E4%BF%A1%E6%81%AF%EF%BC%8C%E5%9C%A8%E6%97%A5%E5%BF%97%E9%87%8C%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0http://www.ip138.com%E5%92%8Chttps://ip.cn%E5%9D%87%E6%97%A0%E6%B3%95%E5%BE%97%E5%88%B0%E5%85%AC%E7%BD%91IP%E4%BF%A1%E6%81%AF%EF%BC%8C%E6%98%AF%E8%BE%93%E5%85%A5%E7%9A%84%E7%BD%91%E5%9D%80%E4%B8%8D%E5%AF%B9%E5%90%97%E3%80%82)

我刚试了下，http://www.ip138.com是因为重定向到了一个无法解析的域名，ip.cn是因为用了CDN防护，我这边解决兼容下试试

**Comment by seszu** [comment]
我又找了几个网站试了下，发现只要是打开出来的页面只是单纯的IP地址的就可以，比如http://ip.3322.net

**Comment by xuchao1213** [comment]
> 我又找了几个网站试了下，发现只要是打开出来的页面只是单纯的IP地址的就可以，比如http://ip.3322.net

1.2.5 published
