### ISSUE TITLE
我的是有两个IPV6地址，一旦临时IPV6地址更新就失效了

### ISSUE THREAD

**Issue by 8373907** [xuchao1213/AliyunDdnsCSharp#21]
CMD>ipconfig /all显示如下：
  IPv6 地址 . . . . . . . . . . . . : XXXXXXXXXXXX:29c5(首选)
   临时 IPv6 地址. . . . . . . . . . : XXXXXXXXXXXX:abbe(受到抨击)
   临时 IPv6 地址. . . . . . . . . . : XXXXXXXXXXXX:4d91(首选)

只有第一个临时IPV6地址的时候，这个DDNS是正常工作的，但第一个临时地址失效后，会获取到第二个临时地址，这时候公网地址是第二个，然而第一个临时地址并不会被系统释放，还是会存在，您开发的插件还是会解析第一个临时地址到阿里云服务器

怎么解决这个问题呢？我不想关闭临时IPV6，毕竟临时IPV6更安全

**Comment by xuchao1213** [comment]
> CMD>ipconfig /all显示如下：
> IPv6 地址 . . . . . . . . . . . . : XXXXXXXXXXXX:29c5(首选)
> 临时 IPv6 地址. . . . . . . . . . : XXXXXXXXXXXX:abbe(受到抨击)
> 临时 IPv6 地址. . . . . . . . . . : XXXXXXXXXXXX:4d91(首选)
> 
> 只有第一个临时IPV6地址的时候，这个DDNS是正常工作的，但第一个临时地址失效后，会获取到第二个临时地址，这时候公网地址是第二个，然而第一个临时地址并不会被系统释放，还是会存在，您开发的插件还是会解析第一个临时地址到阿里云服务器
> 
> 怎么解决这个问题呢？我不想关闭临时IPV6，毕竟临时IPV6更安全

你可以配置一个公网获取IPV6地址的的url,这样就不会取本地网卡地址,如果你就是要获取本地网卡地址的话,我这边需要加一下取本地IPV6地址的策略,

**Comment by 8373907** [comment]
可能我的URL配置地址代码写错了，我再试试，非常感谢
