### ISSUE TITLE
IPV6发生变动会在阿里云产生三条记录

### ISSUE THREAD

**Issue by irrocu** [xuchao1213/AliyunDdnsCSharp#22]
IPV6发生变动会在阿里云产生三条记录，分别是ipv6同步更新的记录、暂停阿里云对这条记录的解析、开启这条记录的解析，一共三条记录，能不能把暂停和开启这两项动作去掉，感觉多余啊，直接更新就行。这样阿里云日志就清爽多了

**Comment by xuchao1213** [comment]
直接更新的话生效可能会有延迟,暂停再启用会加速dns同步,我下个版本加个开关配置

**Comment by irrocu** [comment]
@xuchao1213 太棒了，期待，感谢作者的精彩付出。

**Comment by irrocu** [comment]
期待作者的更新，隔两天就上来看看：）

**Comment by xuchao1213** [comment]
> 期待作者的更新，隔两天就上来看看：）

这两天有点忙,等忙过了这两天我该发布新版 :> ~!

**Comment by yaoniming-158** [comment]
这个程序好用。我使用ipv6
