### ISSUE TITLE
内存越来越大。后期直奔1G内存

### ISSUE THREAD

**Issue by yang9w** [xuchao1213/AliyunDdnsCSharp#24]
不知道问题解决了吗？我用的是1.2.4.0版本

**Comment by netoyou** [comment]
我的客户吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月11日(星期天) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xuchao1213/AliyunDdnsCSharp] 内存越来越大。后期直奔1G内存 (#24)





 
不知道问题解决了吗？我用的是1.2.4.0版本

**Comment by yang9w** [comment]
https://gitee.com/XuChaoProject/AliyunDdnsCSharp/issues/I12L3S
貌似1.2.5.0版本解决了。我已经很久没更新了。哎
