### ISSUE TITLE
会自动删除其他的子域名记录

### ISSUE THREAD

**Issue by yanaex** [xuchao1213/AliyunDdnsCSharp#3]
使用的子域名例如是
xd.qq.com
每次更新解析会把其他 xd开头的子域名给删除
例如
xdfwaffwa.qq.com
xdbsvsdc.qq.com
xdiwjqonr.qq.com
xd21341241.qq.com
已经崩溃了 

![Snipaste_2019-10-08_15-39-19.png](https://i.loli.net/2019/10/08/MtDkhx1epYA2lJO.png)

**Comment by yanaex** [comment]
而且 就算不是xd开头的 其他子域名包含xd的 也会被删除掉。

**Comment by xuchao1213** [comment]
> 而且 就算不是xd开头的 其他子域名包含xd的 也会被删除掉。

应该是查询的时候阿里云返回了所有包含关键字的记录,我这边稍后修复一下

**Comment by yanaex** [comment]
令人窒息，看了半天原来是有BUG
我以为阿里面板出问题了，添加上自动给我删除了

**Comment by xuchao1213** [comment]
> 令人窒息，看了半天原来是有BUG
> 我以为阿里面板出问题了，添加上自动给我删除了

1.2.5 published
