### ISSUE TITLE
日志文件的编码是啥？

### ISSUE THREAD

**Issue by minefujiko9293** [xuchao1213/AliyunDdnsCSharp#30]

**Comment by minefujiko9293** [comment]
请问日志文件的编码是啥？打开乱码，感觉可以同一用utf8

**Comment by xuchao1213** [comment]
> 请问日志文件的编码是啥？打开乱码，感觉可以同一用utf8

使用的是Nlog 库,程序根目录下有个Nlog.config可自行修改编码配置,参考
https://github.com/NLog/NLog/wiki/File-target
