### ISSUE TITLE
大佬，请问一下如何同时解析ipv4和ipv6？

### ISSUE THREAD

**Issue by Arnolwutong** [xuchao1213/AliyunDdnsCSharp#31]
是卸载一个conf文件里还是两个？能不能给个同时解析ipv4和ipv6的模板，我现在只能解析一条，如果解析IPv4了就不解析IPv6了

**Comment by Arnolwutong** [comment]
我现在是这么配置的，不知道问题出在哪
![QQ截图20220508103846](https://user-images.githubusercontent.com/95761056/167279409-34596dda-1be8-41ac-a757-4a330c3be3ca.png)

![QQ截图20220508103951](https://user-images.githubusercontent.com/95761056/167279428-d70cc181-a3cc-4dfe-9532-2ba4b1358483.png)

**Comment by xuchao1213** [comment]
> 是卸载一个conf文件里还是两个？能不能给个同时解析ipv4和ipv6的模板，我现在只能解析一条，如果解析IPv4了就不解析IPv6了

一个配置文件一个,可以同时解析N个的,不论Ipv4还是Ipv6,下面是我自己用的配置
<img width="702" alt="image" src="https://user-images.githubusercontent.com/16534956/167297177-48213b0d-a8bf-47c1-85d4-37add074a013.png">

<img width="941" alt="image" src="https://user-images.githubusercontent.com/16534956/167297299-745afd8d-b309-48a5-8f80-ee78e01d4f8f.png">
