### ISSUE TITLE
本地ipv4地址可以获取吗

### ISSUE THREAD

**Issue by 190854876** [xuchao1213/AliyunDdnsCSharp#34]
有没有一种方法可以将本地ipv4进行映射，几个网址提供的ipv4的地址都不是本地ipv4地址。我之前试着用第三方软件获取本地ipv4,然后使用作者的这个项目解析。有没有办法直接识别本地ipv4,而不通过第三方软件进行映射？

**Comment by xuchao1213** [comment]
> 有没有一种方法可以将本地ipv4进行映射，几个网址提供的ipv4的地址都不是本地ipv4地址。我之前试着用第三方软件获取本地ipv4,然后使用作者的这个项目解析。有没有办法直接识别本地ipv4,而不通过第三方软件进行映射？

本地ipv4地址是指电脑通过dhcp拿到的局域网地址么

**Comment by 190854876** [comment]
是的，就是ipconfig后
ipv4的地址。此时的IPV6是公网网址，而IPV4是局域网内分配的


***@***.***
 
发件人： XuChao
发送时间： 2024-08-29 05:45
收件人： xuchao1213/AliyunDdnsCSharp
抄送： 190854876; Author
主题： Re: [xuchao1213/AliyunDdnsCSharp] 本地ipv4地址可以获取吗 (Issue #34)
有没有一种方法可以将本地ipv4进行映射，几个网址提供的ipv4的地址都不是本地ipv4地址。我之前试着用第三方软件获取本地ipv4,然后使用作者的这个项目解析。有没有办法直接识别本地ipv4,而不通过第三方软件进行映射？
本地ipv4地址是指电脑通过dhcp拿到的局域网地址么

**Comment by xuchao1213** [comment]
已支持，请下载最新版使用

**Comment by 190854876** [comment]
感谢大佬，大佬牛逼，用了好多年了，伴随我的研究生生涯



***@***.***
 
发件人： XuChao
发送时间： 2024-09-07 10:46
收件人： xuchao1213/AliyunDdnsCSharp
抄送： 190854876; Author
主题： Re: [xuchao1213/AliyunDdnsCSharp] 本地ipv4地址可以获取吗 (Issue #34)
已支持，请下载最新版使用
