### ISSUE TITLE
日志里经常出现获取真实地址失败的错误

### ISSUE THREAD

**Issue by xiaoyu1010** [xuchao1213/AliyunDdnsCSharp#5]
ipv6的地址，配置文件里获取ip的[ ]无论留空还是输入底下都地址都有百分之50几率获取失败。

**Comment by xuchao1213** [comment]
> ipv6的地址，配置文件里获取ip的[ ]无论留空还是输入底下都地址都有百分之50几率获取失败。

具体日志贴一下
