### ISSUE TITLE
服务名无效

### ISSUE THREAD

**Issue by xman55555** [xuchao1213/AliyunDdnsCSharp#7]
提示服务名无效，不懂什么意思？是
![image](https://user-images.githubusercontent.com/3001600/69593113-2f3b1880-1033-11ea-8e61-8de5111732a6.png)
哪里没有配置好吗？

**Comment by xuchao1213** [comment]
> 提示服务名无效，不懂什么意思？是
> ![image](https://user-images.githubusercontent.com/3001600/69593113-2f3b1880-1033-11ea-8e61-8de5111732a6.png)
> 哪里没有配置好吗？

操作系统版本是哪个，
安装步骤，解压后直接双击install.bat即可安装成功的
