### ISSUE TITLE
ipconfig获取本机IPv6

### ISSUE THREAD

**Issue by rousongs** [xuchao1213/AliyunDdnsCSharp#8]
```
 "GetIpUrls": [
       "",
      ]
```
配置文件最后一行留空是以ipconfig的方式获取本机ipv6吗？ 在我电脑上测测获取不到IP, 日志提示 fetch real internet ip from  fail，  是不是留空的写法不对？

感谢指导。

**Comment by xuchao1213** [comment]
> ```
>  "GetIpUrls": [
>        "",
>       ]
> ```
> 
> 配置文件最后一行留空是以ipconfig的方式获取本机ipv6吗？ 在我电脑上测测获取不到IP, 日志提示 fetch real internet ip from fail， 是不是留空的写法不对？
> 
> 感谢指导。

留空配置如下：
"GetIpUrls":[],或者直接删除GetIpUrls这个配置项
